services:
  server:
    container_name: notify-server
    image: ${DOCKER_HUB_REPO}/eatbook-notify:deploy
    ports:
      - 3001:3001
      - 6379:6379
    environment:
      - SERVER_PORT=${SERVER_PORT}
    entrypoint: ["sh", "-c"]
    # DB 컨테이너가 완전히 로드되기 이전에 명령어가 실행되면
    # DB 동기화와 시드데이터를 넣을 수 없으므로 일정 시간 멈춤
    # 맨 마지막 구문은 없는 파읽을 읽게해 강제로 컨테이너가 종료되지 않게 함
        # service redis-server start
        # sleep 5
        # npm run start:prod
        # redis-server --port 6379 & 
    command: 
      - |
        sleep 5 && 
        npm run start:prod &&
        tail -f /dev/null